### ISSUE TITLE
maybe switch from yaml to something else for intermediate steps

### ISSUE THREAD

**Issue by vroland** [serlo-org/serlo-export#139]
YAML is quote slow when parsing and serializing:
```
test test::benchmarks::bench_html_export      ... bench:   2,431,580 ns/iter (+/- 579,249)
test test::benchmarks::bench_json_parsing     ... bench:  34,090,311 ns/iter (+/- 6,573,505)
test test::benchmarks::bench_json_serializing ... bench:   1,847,693 ns/iter (+/- 488,248)
test test::benchmarks::bench_latex_export     ... bench:   6,964,696 ns/iter (+/- 1,584,882)
test test::benchmarks::bench_yaml_parsing     ... bench: 110,361,690 ns/iter (+/- 9,401,219)
test test::benchmarks::bench_yaml_serializing ... bench:  62,642,980 ns/iter (+/- 10,198,818)
```
For a lengthy article we have about 170ms of serialization and deserialization compared to 2ms / 6ms for export. Of course, the absolute values don't say much, but the relative run times paint a clear picture.

Leaving this just as a note for later, this optimization is not a priority for now. Although `150ms * 4 passes / article * 100 articles => about 60 seconds` is not insignificant for non-pdf targets.

**Comment by vroland** [comment]
Another bit on performance:
calling python for unescaping strings (`unescape_make.py`) is comparatively slow: For the html print target, the `unescape` function is called 315 times, resulting in a total of runtime of 17s, compared to 66s for the whole export (with cached media and sections, serial build).

**Comment by vroland** [comment]
Another big hit might be texvccheck, though this depends on how math-heavy an article is:
```
Benchmark #1: mk/bin/mfnf_ex latex --texvccheck-path mk/bin/texvccheck < articles/Mathe_für_Nicht-Freaks@COLON@_Epsilon-Delta-Kriterium_der_Stetigkeit/839108.yml
  Time (mean ± σ):     334.9 ms ±   4.7 ms    [User: 311.1 ms, System: 35.9 ms]
  Range (min … max):   329.2 ms … 343.2 ms
 ```
vs 
```
Benchmark #1: mk/bin/mfnf_ex latex < articles/Mathe_für_Nicht-Freaks@COLON@_Epsilon-Delta-Kriterium_der_Stetigkeit/839108.yml
  Time (mean ± σ):     107.1 ms ±   2.9 ms    [User: 96.7 ms, System: 10.5 ms]
  Range (min … max):   105.0 ms … 112.8 ms
```
With cold caching this might be even more drastic.

**Comment by vroland** [comment]
I just added a flag to the parser to output json instead of yaml. Here are some benchmarks:

| Command | Mean [ms] | Min…Max [ms] |
|:---|---:|---:|
| `target/release/mwtoast -i ../mfnf-pdf-export/articles/Mathe_für_Nicht-Freaks@COLON@_Epsilon-Delta-Kriterium_der_Stetigkeit/839108.md  > result.yml` | 175.7 ± 4.0 | 173.2…188.8 |

| Command | Mean [ms] | Min…Max [ms] |
|:---|---:|---:|
| `target/release/mwtoast -i ../mfnf-pdf-export/articles/Mathe_für_Nicht-Freaks@COLON@_Epsilon-Delta-Kriterium_der_Stetigkeit/839108.md --json > result.json` | 52.5 ± 1.6 | 51.2…60.4 |

There is a significant difference in size as well:
```
-rw-r--r-- 1 vroland vroland 501K 22. Nov 12:11 result.json
-rw-r--r-- 1 vroland vroland 1,4M 22. Nov 12:12 result.yml
```

**Comment by vroland** [comment]
serial build time for html/print is now at 38 seconds for me. Looks like using jq to unescape article paths had the most impact performance-wise.

Another bottleneck is texvccheck, as we already know. Currently, tex sanitization is done for every run of mfnf-export. This could be avoided by doing this as a separate step in the build chain.

**Comment by kulla** [comment]
Someone recommended me to use MessagePack ( https://msgpack.org/ ) which shall be faster

**Comment by vroland** [comment]
looks interesting, but might not be easy to integrate, because we use JQ for some processing of JSON files, so we'd need an additional conversion step for these. Furthermore, performance currently seems more limited by I/O performance and shell / process creation overhead...
